/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 01-abr.-2019 10:51:43 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `actividades` CASCADE
;

DROP TABLE IF EXISTS `categorias` CASCADE
;

DROP TABLE IF EXISTS `estudiantes` CASCADE
;

DROP TABLE IF EXISTS `estudiantes_logros` CASCADE
;

DROP TABLE IF EXISTS `logros` CASCADE
;

DROP TABLE IF EXISTS `materias` CASCADE
;

/* Create Tables */

CREATE TABLE `actividades`
(
	`idactividad` INT NOT NULL AUTO_INCREMENT,
	`nombre_actividad` VARCHAR(50) NOT NULL,
	`nota_actividad` VARCHAR(50) NOT NULL,
	`idcategoria` INT NULL,
	CONSTRAINT `PK_actividades` PRIMARY KEY (`idactividad` ASC)
)

;

CREATE TABLE `categorias`
(
	`idcategoria` INT NOT NULL AUTO_INCREMENT,
	`nombre_categoria` VARCHAR(50) NOT NULL,
	`porcentaje` INT NOT NULL,
	`nota_categoria` INT NOT NULL,
	`idmateria` INT NULL,
	CONSTRAINT `PK_categorias` PRIMARY KEY (`idcategoria` ASC)
)

;

CREATE TABLE `estudiantes`
(
	`idestudiante` INT NOT NULL AUTO_INCREMENT,
	`nombre_estudiante` VARCHAR(50) NOT NULL,
	`apellido_estudiante` VARCHAR(50) NOT NULL,
	`correo` VARCHAR(50) NOT NULL,
	`contrasenia` VARCHAR(50) NOT NULL,
	CONSTRAINT `PK_estudiantes` PRIMARY KEY (`idestudiante` ASC)
)

;

CREATE TABLE `estudiantes_logros`
(
	`idEstudiante_logro` INT NOT NULL AUTO_INCREMENT,
	`estado` INT NULL,
	`idLogro` INT NULL,
	`idestudiante` INT NULL,
	CONSTRAINT `PK_estudiantes_logros` PRIMARY KEY (`idEstudiante_logro` ASC)
)

;

CREATE TABLE `logros`
(
	`idLogro` INT NOT NULL AUTO_INCREMENT,
	`nombre_logro` VARCHAR(50) NOT NULL,
	CONSTRAINT `PK_Logros` PRIMARY KEY (`idLogro` ASC)
)

;

CREATE TABLE `materias`
(
	`idmateria` INT NOT NULL AUTO_INCREMENT,
	`nombre_materia` VARCHAR(50) NOT NULL,
	`nota_materia` VARCHAR(50) NOT NULL,
	`hora` VARCHAR(50) NOT NULL,
	`idestudiante` INT NULL,
	CONSTRAINT `PK_Materias` PRIMARY KEY (`idmateria` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `actividades` 
 ADD INDEX `IXFK_actividades_categorias` (`idcategoria` ASC)
;

ALTER TABLE `categorias` 
 ADD INDEX `IXFK_categorias_Materias` (`idmateria` ASC)
;

ALTER TABLE `estudiantes_logros` 
 ADD INDEX `IXFK_estudiantes_logros_estudiantes` (`idestudiante` ASC)
;

ALTER TABLE `estudiantes_logros` 
 ADD INDEX `IXFK_estudiantes_logros_Logros` (`idLogro` ASC)
;

ALTER TABLE `materias` 
 ADD INDEX `IXFK_Materias_estudiantes` (`idestudiante` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `actividades` 
 ADD CONSTRAINT `FK_actividades_categorias`
	FOREIGN KEY (`idcategoria`) REFERENCES `categorias` (`idcategoria`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `categorias` 
 ADD CONSTRAINT `FK_categorias_Materias`
	FOREIGN KEY (`idmateria`) REFERENCES `materias` (`idmateria`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `estudiantes_logros` 
 ADD CONSTRAINT `FK_estudiantes_logros_estudiantes`
	FOREIGN KEY (`idestudiante`) REFERENCES `estudiantes` (`idestudiante`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `estudiantes_logros` 
 ADD CONSTRAINT `FK_estudiantes_logros_Logros`
	FOREIGN KEY (`idLogro`) REFERENCES `logros` (`idLogro`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `materias` 
 ADD CONSTRAINT `FK_Materias_estudiantes`
	FOREIGN KEY (`idestudiante`) REFERENCES `estudiantes` (`idestudiante`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1 
;
